// pages/_app.js
import { Inter } from "next/font/google";
import Header from "../components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <main>
        {children}
      </main>
    </>
  );
}
